name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on:
    - "ubuntu-latest"
    - "windows-latest"
    - "macos-latest"
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
